name: Build Windows EXE

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main, master ]
    paths:
      - 'demo.py'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: 打包exe
      run: |
        pyinstaller --onefile --windowed --name=心形弹窗提示 --clean demo.py
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: 心形弹窗提示-Windows
        path: dist/心形弹窗提示.exe

